@startuml

@startuml
skinparam usecase {
backgroundColor DeepSkyBlue
BorderColor DarkSlateGray
ArrowColor Blue
}

skinparam Note {
BackgroundColor LightBlue
BorderColor Blue
}

skinparam roundcorner 20

skinparam actor {
FontName Arial
Style awesome
BorderColor DeepSkyBlue
BackgroundColor LightBlue
}

actor Drinker
actor Bartender

loop until drunk
Drinker -> Drinker : Creates Drink Oder
Drinker -> Bartender : Gives DrinkOrder to Bartender
Bartender -> Bartender : Mixes Substances (alchol and mix)\ninto Medications (mixed drinks)
Bartender -> Drinker : Dispenses Tasty MixedDrink to Drinker
Drinker -> Drinker : Consumes Drink
end
Bartender -> Drinker : Hands bill for payment
Drinker -> Bartender : Pays Bill
@enduml