@startuml

!theme cerulean



[*] -> Sober 
Sober : It's hot and\n I'm thirsty
Sober -> Drinking
state Drinking {
[*] -right-> OrderDrink
OrderDrink -right-> MakeDrink
MakeDrink -down-> GiveDrink
GiveDrink -> DrinkDrink
DrinkDrink -> OrderDrink
DrinkDrink -right-> DrankDrink
DrankDrink -> OrderDrink
}
GiveDrink -> DropDrink
DropDrink -> Drunk
Drunk -> [*]
@enduml